### ISSUE TITLE
Add a "save to/open from file" feature

### ISSUE THREAD

**Issue by Zasco** [noah-severyn/YamlEditorForSc4pac#31]
Add a button that would save the current YAML metadata to a file. The default file name would be the (first found) package name.

Add a button that would load YAML metadata from a file.

Override "_ctrl + s_" and "_ctrl + o_" to save and open a file.

**Comment by noah-severyn** [comment]
I'm not sure what the best way would be to pull this data from a channel / Github.

**Comment by Zasco** [comment]
> I'm not sure what the best way would be to pull this data from a channel / Github.

Use the Github API. For instance, [here](https://api.github.com/repos/memo33/sc4pac/git/trees/2b987426294c3fb8b66b1875d629d5937ad921ac) you get the list of directories in [memo/sc4pac](https://github.com/memo33/sc4pac)'s "[**src/yaml**](https://github.com/memo33/sc4pac/tree/main/src/yaml)".
